name = "coin-planet-api"
main = "src/index.ts"
compatibility_date = "2026-04-04"
workers_dev = true

[[routes]]
pattern = "api.coinplanets.net"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "coin-planet-db"
database_id = "6fc57b82-5ec7-47b8-a3a4-4b00a23af41c"

[[kv_namespaces]]
binding = "CACHE"
id = "06f37a3d8b3d4880ad2061397ddd4bb2"

[vars]
CHAIN_ID = "56"
RPC_URL = "https://bsc-dataseed.binance.org/"
SUPER_TOKEN_ADDRESS = "0x427cf0ddFA97cf7a10F009810e07D8F935e5ec4e"
MINING_POOL_ADDRESS = "0xf275de50784AEbE13a5C86eEEbB96ef83CC01F54"
SWAP_ROUTER_ADDRESS = "0x3E9305BEca013582BC484d78C8dA7a82e8b47a1B"
OWNER_ADDRESS = "0x571f87436C7bd84327d3b751BB911Bbc3E19bF56"
ADMIN_ADDRESSES = ""
SUB_ADMIN_ADDRESSES = "0xca949919f03E3e52949d1436442312D8A023fE41"
USDT_TOKEN_ADDRESS = "0x55d398326f99059fF775485246999027B3197955"
OWNER_MINT_DAILY_CAP = "5000000"
BSC_RPC_UPSTREAMS = "https://bsc-dataseed.binance.org/,https://bsc-dataseed1.defibit.io/,https://bsc-dataseed1.ninicoin.io/,https://bsc.publicnode.com,https://rpc.ankr.com/bsc"

[[r2_buckets]]
binding = "APP_BUCKET"
bucket_name = "coin-planet-apps"

[triggers]
crons = ["*/15 * * * *"]
