name = "coin-planet-api"
main = "src/index.ts"
compatibility_date = "2026-04-04"
workers_dev = true

[[routes]]
pattern = "api.coinplanets.net"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "coin-planet-db"
database_id = "6fc57b82-5ec7-47b8-a3a4-4b00a23af41c"

[[kv_namespaces]]
binding = "CACHE"
id = "06f37a3d8b3d4880ad2061397ddd4bb2"

[vars]
JWT_SECRET = "YzQ0ODY2OTAtMGIyZi00NzAxLWE4YjItYWRkMjEyYmVmNzhiMmQ5M2QwMDEtYjk0Yy00NmI0LWIyNDEtNDU0ZGZmNWIwM2M1"
CHAIN_ID = "56"
RPC_URL = "https://bsc-dataseed.binance.org/"
SUPER_TOKEN_ADDRESS = "0x88eF10cA51B75a9dBe600eeE7aCFDd71121D4118"
MINING_POOL_ADDRESS = "0xC1Ad01d383f736e1D9DD635b6D6b26a92D7a81e7"
SWAP_ROUTER_ADDRESS = "0x865a15341463D1a9E59ed92ff8f7229fA22DE6c7"
OWNER_ADDRESS = "0x571f87436C7bd84327d3b751BB911Bbc3E19bF56"
ADMIN_ADDRESSES = "0xca949919f03E3e52949d1436442312D8A023fE41"
USDT_TOKEN_ADDRESS = "0xe2851f5FF214e68a0629baefF96B5020D9c708dB"
OWNER_MINT_DAILY_CAP = "5000000"

[[r2_buckets]]
binding = "APP_BUCKET"
bucket_name = "coin-planet-apps"

[triggers]
crons = ["*/15 * * * *"]