/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MiningPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_EMISSION"
      | "MAX_HASHRATE"
      | "MIN_HASHRATE"
      | "addAdmin"
      | "adjustDifficulty"
      | "adminCount"
      | "availableRewardBalance"
      | "bindReferral"
      | "calculatePendingReward"
      | "claimCooldown"
      | "claimReward"
      | "deactivateMiner"
      | "difficultyAdjustmentPeriod"
      | "eligibleHashrateIncluded"
      | "getAdmins"
      | "getGlobalStats"
      | "getMinerInfo"
      | "globalHashrate"
      | "initialize"
      | "isAdmin"
      | "isRewardEligible"
      | "lastDifficultyAdjustment"
      | "lockupPeriod"
      | "minSuperStakeForReward"
      | "minerAddressKnown"
      | "minerAddresses"
      | "miners"
      | "owner"
      | "proxiableUUID"
      | "referrerOf"
      | "registerMiner"
      | "registeredMiners"
      | "removeAdmin"
      | "renounceOwnership"
      | "rewardPerHashPerDay"
      | "setMinSuperStakeForReward"
      | "stakeSuper"
      | "stakedSuper"
      | "superToken"
      | "syncMinerEligibility"
      | "totalActiveHashrate"
      | "totalEligibleHashrate"
      | "totalEmitted"
      | "totalMiners"
      | "totalStakedSuper"
      | "transferOwnership"
      | "unstakeSuper"
      | "updateHashrate"
      | "updateRewardParameters"
      | "upgradeTo"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminChanged"
      | "AdminRemoved"
      | "BeaconUpgraded"
      | "DifficultyAdjusted"
      | "HashrateUpdated"
      | "Initialized"
      | "MinSuperStakeForRewardUpdated"
      | "MinerDeactivated"
      | "MinerEligibilityUpdated"
      | "MinerRegistered"
      | "OwnershipTransferred"
      | "ReferralBound"
      | "RewardClaimed"
      | "RewardParametersUpdated"
      | "SuperStaked"
      | "SuperUnstaked"
      | "SuspiciousActivityDetected"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_EMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HASHRATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_HASHRATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adjustDifficulty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableRewardBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bindReferral",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePendingReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateMiner",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "difficultyAdjustmentPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eligibleHashrateIncluded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getAdmins", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalHashrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRewardEligible",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastDifficultyAdjustment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockupPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minSuperStakeForReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minerAddressKnown",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minerAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "miners", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "referrerOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerMiner",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredMiners",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerHashPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinSuperStakeForReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeSuper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedSuper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "superToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "syncMinerEligibility",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "totalActiveHashrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEligibleHashrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEmitted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMiners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalStakedSuper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeSuper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHashrate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardParameters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeTo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAILY_EMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HASHRATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_HASHRATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adjustDifficulty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "adminCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableRewardBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bindReferral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "difficultyAdjustmentPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibleHashrateIncluded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRewardEligible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDifficultyAdjustment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockupPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minSuperStakeForReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minerAddressKnown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minerAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "miners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "referrerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredMiners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerHashPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinSuperStakeForReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeSuper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakedSuper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "syncMinerEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalActiveHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEligibleHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMiners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalStakedSuper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeSuper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike, operator: AddressLike];
  export type OutputTuple = [admin: string, operator: string];
  export interface OutputObject {
    admin: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminChangedEvent {
  export type InputTuple = [previousAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [previousAdmin: string, newAdmin: string];
  export interface OutputObject {
    previousAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [admin: AddressLike, operator: AddressLike];
  export type OutputTuple = [admin: string, operator: string];
  export interface OutputObject {
    admin: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeaconUpgradedEvent {
  export type InputTuple = [beacon: AddressLike];
  export type OutputTuple = [beacon: string];
  export interface OutputObject {
    beacon: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DifficultyAdjustedEvent {
  export type InputTuple = [newGlobalHashrate: BigNumberish];
  export type OutputTuple = [newGlobalHashrate: bigint];
  export interface OutputObject {
    newGlobalHashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashrateUpdatedEvent {
  export type InputTuple = [
    miner: AddressLike,
    oldHashrate: BigNumberish,
    newHashrate: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    oldHashrate: bigint,
    newHashrate: bigint
  ];
  export interface OutputObject {
    miner: string;
    oldHashrate: bigint;
    newHashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinSuperStakeForRewardUpdatedEvent {
  export type InputTuple = [oldAmount: BigNumberish, newAmount: BigNumberish];
  export type OutputTuple = [oldAmount: bigint, newAmount: bigint];
  export interface OutputObject {
    oldAmount: bigint;
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerDeactivatedEvent {
  export type InputTuple = [miner: AddressLike, reason: string];
  export type OutputTuple = [miner: string, reason: string];
  export interface OutputObject {
    miner: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerEligibilityUpdatedEvent {
  export type InputTuple = [
    miner: AddressLike,
    eligible: boolean,
    hashrate: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    eligible: boolean,
    hashrate: bigint
  ];
  export interface OutputObject {
    miner: string;
    eligible: boolean;
    hashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerRegisteredEvent {
  export type InputTuple = [miner: AddressLike, hashrate: BigNumberish];
  export type OutputTuple = [miner: string, hashrate: bigint];
  export interface OutputObject {
    miner: string;
    hashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferralBoundEvent {
  export type InputTuple = [invitee: AddressLike, inviter: AddressLike];
  export type OutputTuple = [invitee: string, inviter: string];
  export interface OutputObject {
    invitee: string;
    inviter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [miner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [miner: string, amount: bigint];
  export interface OutputObject {
    miner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardParametersUpdatedEvent {
  export type InputTuple = [
    newRewardPerHash: BigNumberish,
    newClaimCooldown: BigNumberish
  ];
  export type OutputTuple = [
    newRewardPerHash: bigint,
    newClaimCooldown: bigint
  ];
  export interface OutputObject {
    newRewardPerHash: bigint;
    newClaimCooldown: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuperStakedEvent {
  export type InputTuple = [
    miner: AddressLike,
    amount: BigNumberish,
    totalStakedByMiner: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    amount: bigint,
    totalStakedByMiner: bigint
  ];
  export interface OutputObject {
    miner: string;
    amount: bigint;
    totalStakedByMiner: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuperUnstakedEvent {
  export type InputTuple = [
    miner: AddressLike,
    amount: BigNumberish,
    totalStakedByMiner: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    amount: bigint,
    totalStakedByMiner: bigint
  ];
  export interface OutputObject {
    miner: string;
    amount: bigint;
    totalStakedByMiner: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspiciousActivityDetectedEvent {
  export type InputTuple = [
    miner: AddressLike,
    score: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [miner: string, score: bigint, reason: string];
  export interface OutputObject {
    miner: string;
    score: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MiningPool extends BaseContract {
  connect(runner?: ContractRunner | null): MiningPool;
  waitForDeployment(): Promise<this>;

  interface: MiningPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_EMISSION: TypedContractMethod<[], [bigint], "view">;

  MAX_HASHRATE: TypedContractMethod<[], [bigint], "view">;

  MIN_HASHRATE: TypedContractMethod<[], [bigint], "view">;

  addAdmin: TypedContractMethod<[account: AddressLike], [void], "nonpayable">;

  adjustDifficulty: TypedContractMethod<[], [void], "nonpayable">;

  adminCount: TypedContractMethod<[], [bigint], "view">;

  availableRewardBalance: TypedContractMethod<[], [bigint], "view">;

  bindReferral: TypedContractMethod<
    [_inviter: AddressLike],
    [void],
    "nonpayable"
  >;

  calculatePendingReward: TypedContractMethod<
    [_miner: AddressLike],
    [bigint],
    "view"
  >;

  claimCooldown: TypedContractMethod<[], [bigint], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  deactivateMiner: TypedContractMethod<
    [_miner: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  difficultyAdjustmentPeriod: TypedContractMethod<[], [bigint], "view">;

  eligibleHashrateIncluded: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAdmins: TypedContractMethod<[], [string[]], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalEm: bigint;
        totalActive: bigint;
        minerCount: bigint;
        totalEligible: bigint;
        totalStaked: bigint;
        minStakeForReward: bigint;
        rewardBalance: bigint;
      }
    ],
    "view"
  >;

  getMinerInfo: TypedContractMethod<
    [_miner: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, boolean] & {
        hashrate: bigint;
        pending: bigint;
        totalClaimed: bigint;
        active: boolean;
        suspiciousScore: bigint;
        stakedAmount: bigint;
        rewardEligible: boolean;
      }
    ],
    "view"
  >;

  globalHashrate: TypedContractMethod<[], [bigint], "view">;

  initialize: TypedContractMethod<
    [_superToken: AddressLike, initialAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  isAdmin: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isRewardEligible: TypedContractMethod<
    [_miner: AddressLike],
    [boolean],
    "view"
  >;

  lastDifficultyAdjustment: TypedContractMethod<[], [bigint], "view">;

  lockupPeriod: TypedContractMethod<[], [bigint], "view">;

  minSuperStakeForReward: TypedContractMethod<[], [bigint], "view">;

  minerAddressKnown: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  minerAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  miners: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        lastClaimed: bigint;
        pendingReward: bigint;
        totalClaimed: bigint;
        registeredTime: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  referrerOf: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerMiner: TypedContractMethod<
    [_hashrate: BigNumberish, _deviceId: string],
    [void],
    "nonpayable"
  >;

  registeredMiners: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  removeAdmin: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardPerHashPerDay: TypedContractMethod<[], [bigint], "view">;

  setMinSuperStakeForReward: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeSuper: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakedSuper: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  superToken: TypedContractMethod<[], [string], "view">;

  syncMinerEligibility: TypedContractMethod<
    [_miners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  totalActiveHashrate: TypedContractMethod<[], [bigint], "view">;

  totalEligibleHashrate: TypedContractMethod<[], [bigint], "view">;

  totalEmitted: TypedContractMethod<[], [bigint], "view">;

  totalMiners: TypedContractMethod<[], [bigint], "view">;

  totalStakedSuper: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeSuper: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateHashrate: TypedContractMethod<
    [_newHashrate: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRewardParameters: TypedContractMethod<
    [_rewardPerHash: BigNumberish, _claimCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeTo: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_EMISSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_HASHRATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_HASHRATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adjustDifficulty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableRewardBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bindReferral"
  ): TypedContractMethod<[_inviter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculatePendingReward"
  ): TypedContractMethod<[_miner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateMiner"
  ): TypedContractMethod<
    [_miner: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "difficultyAdjustmentPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eligibleHashrateIncluded"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAdmins"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalEm: bigint;
        totalActive: bigint;
        minerCount: bigint;
        totalEligible: bigint;
        totalStaked: bigint;
        minStakeForReward: bigint;
        rewardBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinerInfo"
  ): TypedContractMethod<
    [_miner: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, boolean] & {
        hashrate: bigint;
        pending: bigint;
        totalClaimed: bigint;
        active: boolean;
        suspiciousScore: bigint;
        stakedAmount: bigint;
        rewardEligible: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalHashrate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_superToken: AddressLike, initialAdmin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRewardEligible"
  ): TypedContractMethod<[_miner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastDifficultyAdjustment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockupPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minSuperStakeForReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minerAddressKnown"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "minerAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "miners"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        lastClaimed: bigint;
        pendingReward: bigint;
        totalClaimed: bigint;
        registeredTime: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "referrerOf"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerMiner"
  ): TypedContractMethod<
    [_hashrate: BigNumberish, _deviceId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredMiners"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPerHashPerDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMinSuperStakeForReward"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeSuper"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakedSuper"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "superToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "syncMinerEligibility"
  ): TypedContractMethod<[_miners: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalActiveHashrate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEligibleHashrate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEmitted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMiners"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalStakedSuper"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeSuper"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHashrate"
  ): TypedContractMethod<[_newHashrate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRewardParameters"
  ): TypedContractMethod<
    [_rewardPerHash: BigNumberish, _claimCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeTo"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminChanged"
  ): TypedContractEvent<
    AdminChangedEvent.InputTuple,
    AdminChangedEvent.OutputTuple,
    AdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "BeaconUpgraded"
  ): TypedContractEvent<
    BeaconUpgradedEvent.InputTuple,
    BeaconUpgradedEvent.OutputTuple,
    BeaconUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "DifficultyAdjusted"
  ): TypedContractEvent<
    DifficultyAdjustedEvent.InputTuple,
    DifficultyAdjustedEvent.OutputTuple,
    DifficultyAdjustedEvent.OutputObject
  >;
  getEvent(
    key: "HashrateUpdated"
  ): TypedContractEvent<
    HashrateUpdatedEvent.InputTuple,
    HashrateUpdatedEvent.OutputTuple,
    HashrateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MinSuperStakeForRewardUpdated"
  ): TypedContractEvent<
    MinSuperStakeForRewardUpdatedEvent.InputTuple,
    MinSuperStakeForRewardUpdatedEvent.OutputTuple,
    MinSuperStakeForRewardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinerDeactivated"
  ): TypedContractEvent<
    MinerDeactivatedEvent.InputTuple,
    MinerDeactivatedEvent.OutputTuple,
    MinerDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MinerEligibilityUpdated"
  ): TypedContractEvent<
    MinerEligibilityUpdatedEvent.InputTuple,
    MinerEligibilityUpdatedEvent.OutputTuple,
    MinerEligibilityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinerRegistered"
  ): TypedContractEvent<
    MinerRegisteredEvent.InputTuple,
    MinerRegisteredEvent.OutputTuple,
    MinerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReferralBound"
  ): TypedContractEvent<
    ReferralBoundEvent.InputTuple,
    ReferralBoundEvent.OutputTuple,
    ReferralBoundEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardParametersUpdated"
  ): TypedContractEvent<
    RewardParametersUpdatedEvent.InputTuple,
    RewardParametersUpdatedEvent.OutputTuple,
    RewardParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SuperStaked"
  ): TypedContractEvent<
    SuperStakedEvent.InputTuple,
    SuperStakedEvent.OutputTuple,
    SuperStakedEvent.OutputObject
  >;
  getEvent(
    key: "SuperUnstaked"
  ): TypedContractEvent<
    SuperUnstakedEvent.InputTuple,
    SuperUnstakedEvent.OutputTuple,
    SuperUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "SuspiciousActivityDetected"
  ): TypedContractEvent<
    SuspiciousActivityDetectedEvent.InputTuple,
    SuspiciousActivityDetectedEvent.OutputTuple,
    SuspiciousActivityDetectedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address,address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminChanged(address,address)": TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;
    AdminChanged: TypedContractEvent<
      AdminChangedEvent.InputTuple,
      AdminChangedEvent.OutputTuple,
      AdminChangedEvent.OutputObject
    >;

    "AdminRemoved(address,address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "BeaconUpgraded(address)": TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;
    BeaconUpgraded: TypedContractEvent<
      BeaconUpgradedEvent.InputTuple,
      BeaconUpgradedEvent.OutputTuple,
      BeaconUpgradedEvent.OutputObject
    >;

    "DifficultyAdjusted(uint256)": TypedContractEvent<
      DifficultyAdjustedEvent.InputTuple,
      DifficultyAdjustedEvent.OutputTuple,
      DifficultyAdjustedEvent.OutputObject
    >;
    DifficultyAdjusted: TypedContractEvent<
      DifficultyAdjustedEvent.InputTuple,
      DifficultyAdjustedEvent.OutputTuple,
      DifficultyAdjustedEvent.OutputObject
    >;

    "HashrateUpdated(address,uint256,uint256)": TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;
    HashrateUpdated: TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MinSuperStakeForRewardUpdated(uint256,uint256)": TypedContractEvent<
      MinSuperStakeForRewardUpdatedEvent.InputTuple,
      MinSuperStakeForRewardUpdatedEvent.OutputTuple,
      MinSuperStakeForRewardUpdatedEvent.OutputObject
    >;
    MinSuperStakeForRewardUpdated: TypedContractEvent<
      MinSuperStakeForRewardUpdatedEvent.InputTuple,
      MinSuperStakeForRewardUpdatedEvent.OutputTuple,
      MinSuperStakeForRewardUpdatedEvent.OutputObject
    >;

    "MinerDeactivated(address,string)": TypedContractEvent<
      MinerDeactivatedEvent.InputTuple,
      MinerDeactivatedEvent.OutputTuple,
      MinerDeactivatedEvent.OutputObject
    >;
    MinerDeactivated: TypedContractEvent<
      MinerDeactivatedEvent.InputTuple,
      MinerDeactivatedEvent.OutputTuple,
      MinerDeactivatedEvent.OutputObject
    >;

    "MinerEligibilityUpdated(address,bool,uint256)": TypedContractEvent<
      MinerEligibilityUpdatedEvent.InputTuple,
      MinerEligibilityUpdatedEvent.OutputTuple,
      MinerEligibilityUpdatedEvent.OutputObject
    >;
    MinerEligibilityUpdated: TypedContractEvent<
      MinerEligibilityUpdatedEvent.InputTuple,
      MinerEligibilityUpdatedEvent.OutputTuple,
      MinerEligibilityUpdatedEvent.OutputObject
    >;

    "MinerRegistered(address,uint256)": TypedContractEvent<
      MinerRegisteredEvent.InputTuple,
      MinerRegisteredEvent.OutputTuple,
      MinerRegisteredEvent.OutputObject
    >;
    MinerRegistered: TypedContractEvent<
      MinerRegisteredEvent.InputTuple,
      MinerRegisteredEvent.OutputTuple,
      MinerRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReferralBound(address,address)": TypedContractEvent<
      ReferralBoundEvent.InputTuple,
      ReferralBoundEvent.OutputTuple,
      ReferralBoundEvent.OutputObject
    >;
    ReferralBound: TypedContractEvent<
      ReferralBoundEvent.InputTuple,
      ReferralBoundEvent.OutputTuple,
      ReferralBoundEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardParametersUpdated(uint256,uint256)": TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;
    RewardParametersUpdated: TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;

    "SuperStaked(address,uint256,uint256)": TypedContractEvent<
      SuperStakedEvent.InputTuple,
      SuperStakedEvent.OutputTuple,
      SuperStakedEvent.OutputObject
    >;
    SuperStaked: TypedContractEvent<
      SuperStakedEvent.InputTuple,
      SuperStakedEvent.OutputTuple,
      SuperStakedEvent.OutputObject
    >;

    "SuperUnstaked(address,uint256,uint256)": TypedContractEvent<
      SuperUnstakedEvent.InputTuple,
      SuperUnstakedEvent.OutputTuple,
      SuperUnstakedEvent.OutputObject
    >;
    SuperUnstaked: TypedContractEvent<
      SuperUnstakedEvent.InputTuple,
      SuperUnstakedEvent.OutputTuple,
      SuperUnstakedEvent.OutputObject
    >;

    "SuspiciousActivityDetected(address,uint256,string)": TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;
    SuspiciousActivityDetected: TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
