/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MiningPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_EMISSION"
      | "MAX_HASHRATE"
      | "MIN_HASHRATE"
      | "adjustDifficulty"
      | "calculatePendingReward"
      | "claimCooldown"
      | "claimReward"
      | "deactivateMiner"
      | "difficultyAdjustmentPeriod"
      | "getGlobalStats"
      | "getMinerInfo"
      | "globalHashrate"
      | "lastDifficultyAdjustment"
      | "lockupPeriod"
      | "miners"
      | "owner"
      | "registerMiner"
      | "registeredMiners"
      | "renounceOwnership"
      | "rewardPerHashPerDay"
      | "superToken"
      | "totalActiveHashrate"
      | "totalEmitted"
      | "totalMiners"
      | "transferOwnership"
      | "updateHashrate"
      | "updateRewardParameters"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DifficultyAdjusted"
      | "HashrateUpdated"
      | "MinerDeactivated"
      | "MinerRegistered"
      | "OwnershipTransferred"
      | "RewardClaimed"
      | "RewardParametersUpdated"
      | "SuspiciousActivityDetected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_EMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HASHRATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_HASHRATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adjustDifficulty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePendingReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateMiner",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "difficultyAdjustmentPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinerInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalHashrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDifficultyAdjustment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lockupPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "miners", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerMiner",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredMiners",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardPerHashPerDay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "superToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalActiveHashrate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEmitted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMiners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHashrate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRewardParameters",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAILY_EMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HASHRATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_HASHRATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adjustDifficulty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "difficultyAdjustmentPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDifficultyAdjustment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockupPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "miners", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerMiner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredMiners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardPerHashPerDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalActiveHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMiners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateHashrate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRewardParameters",
    data: BytesLike
  ): Result;
}

export namespace DifficultyAdjustedEvent {
  export type InputTuple = [newGlobalHashrate: BigNumberish];
  export type OutputTuple = [newGlobalHashrate: bigint];
  export interface OutputObject {
    newGlobalHashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HashrateUpdatedEvent {
  export type InputTuple = [
    miner: AddressLike,
    oldHashrate: BigNumberish,
    newHashrate: BigNumberish
  ];
  export type OutputTuple = [
    miner: string,
    oldHashrate: bigint,
    newHashrate: bigint
  ];
  export interface OutputObject {
    miner: string;
    oldHashrate: bigint;
    newHashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerDeactivatedEvent {
  export type InputTuple = [miner: AddressLike, reason: string];
  export type OutputTuple = [miner: string, reason: string];
  export interface OutputObject {
    miner: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinerRegisteredEvent {
  export type InputTuple = [miner: AddressLike, hashrate: BigNumberish];
  export type OutputTuple = [miner: string, hashrate: bigint];
  export interface OutputObject {
    miner: string;
    hashrate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [miner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [miner: string, amount: bigint];
  export interface OutputObject {
    miner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardParametersUpdatedEvent {
  export type InputTuple = [
    newRewardPerHash: BigNumberish,
    newClaimCooldown: BigNumberish
  ];
  export type OutputTuple = [
    newRewardPerHash: bigint,
    newClaimCooldown: bigint
  ];
  export interface OutputObject {
    newRewardPerHash: bigint;
    newClaimCooldown: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuspiciousActivityDetectedEvent {
  export type InputTuple = [
    miner: AddressLike,
    score: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [miner: string, score: bigint, reason: string];
  export interface OutputObject {
    miner: string;
    score: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MiningPool extends BaseContract {
  connect(runner?: ContractRunner | null): MiningPool;
  waitForDeployment(): Promise<this>;

  interface: MiningPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_EMISSION: TypedContractMethod<[], [bigint], "view">;

  MAX_HASHRATE: TypedContractMethod<[], [bigint], "view">;

  MIN_HASHRATE: TypedContractMethod<[], [bigint], "view">;

  adjustDifficulty: TypedContractMethod<[], [void], "nonpayable">;

  calculatePendingReward: TypedContractMethod<
    [_miner: AddressLike],
    [bigint],
    "view"
  >;

  claimCooldown: TypedContractMethod<[], [bigint], "view">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  deactivateMiner: TypedContractMethod<
    [_miner: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;

  difficultyAdjustmentPeriod: TypedContractMethod<[], [bigint], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalEm: bigint;
        totalActive: bigint;
        minerCount: bigint;
      }
    ],
    "view"
  >;

  getMinerInfo: TypedContractMethod<
    [_miner: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        pending: bigint;
        totalClaimed: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;

  globalHashrate: TypedContractMethod<[], [bigint], "view">;

  lastDifficultyAdjustment: TypedContractMethod<[], [bigint], "view">;

  lockupPeriod: TypedContractMethod<[], [bigint], "view">;

  miners: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        lastClaimed: bigint;
        pendingReward: bigint;
        totalClaimed: bigint;
        registeredTime: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerMiner: TypedContractMethod<
    [_hashrate: BigNumberish, _deviceId: string],
    [void],
    "nonpayable"
  >;

  registeredMiners: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardPerHashPerDay: TypedContractMethod<[], [bigint], "view">;

  superToken: TypedContractMethod<[], [string], "view">;

  totalActiveHashrate: TypedContractMethod<[], [bigint], "view">;

  totalEmitted: TypedContractMethod<[], [bigint], "view">;

  totalMiners: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateHashrate: TypedContractMethod<
    [_newHashrate: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateRewardParameters: TypedContractMethod<
    [_rewardPerHash: BigNumberish, _claimCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_EMISSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_HASHRATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_HASHRATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adjustDifficulty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculatePendingReward"
  ): TypedContractMethod<[_miner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateMiner"
  ): TypedContractMethod<
    [_miner: AddressLike, _reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "difficultyAdjustmentPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalEm: bigint;
        totalActive: bigint;
        minerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMinerInfo"
  ): TypedContractMethod<
    [_miner: AddressLike],
    [
      [bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        pending: bigint;
        totalClaimed: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalHashrate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDifficultyAdjustment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockupPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "miners"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint] & {
        hashrate: bigint;
        lastClaimed: bigint;
        pendingReward: bigint;
        totalClaimed: bigint;
        registeredTime: bigint;
        active: boolean;
        suspiciousScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerMiner"
  ): TypedContractMethod<
    [_hashrate: BigNumberish, _deviceId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredMiners"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardPerHashPerDay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "superToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalActiveHashrate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEmitted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMiners"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateHashrate"
  ): TypedContractMethod<[_newHashrate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateRewardParameters"
  ): TypedContractMethod<
    [_rewardPerHash: BigNumberish, _claimCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DifficultyAdjusted"
  ): TypedContractEvent<
    DifficultyAdjustedEvent.InputTuple,
    DifficultyAdjustedEvent.OutputTuple,
    DifficultyAdjustedEvent.OutputObject
  >;
  getEvent(
    key: "HashrateUpdated"
  ): TypedContractEvent<
    HashrateUpdatedEvent.InputTuple,
    HashrateUpdatedEvent.OutputTuple,
    HashrateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinerDeactivated"
  ): TypedContractEvent<
    MinerDeactivatedEvent.InputTuple,
    MinerDeactivatedEvent.OutputTuple,
    MinerDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "MinerRegistered"
  ): TypedContractEvent<
    MinerRegisteredEvent.InputTuple,
    MinerRegisteredEvent.OutputTuple,
    MinerRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardParametersUpdated"
  ): TypedContractEvent<
    RewardParametersUpdatedEvent.InputTuple,
    RewardParametersUpdatedEvent.OutputTuple,
    RewardParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SuspiciousActivityDetected"
  ): TypedContractEvent<
    SuspiciousActivityDetectedEvent.InputTuple,
    SuspiciousActivityDetectedEvent.OutputTuple,
    SuspiciousActivityDetectedEvent.OutputObject
  >;

  filters: {
    "DifficultyAdjusted(uint256)": TypedContractEvent<
      DifficultyAdjustedEvent.InputTuple,
      DifficultyAdjustedEvent.OutputTuple,
      DifficultyAdjustedEvent.OutputObject
    >;
    DifficultyAdjusted: TypedContractEvent<
      DifficultyAdjustedEvent.InputTuple,
      DifficultyAdjustedEvent.OutputTuple,
      DifficultyAdjustedEvent.OutputObject
    >;

    "HashrateUpdated(address,uint256,uint256)": TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;
    HashrateUpdated: TypedContractEvent<
      HashrateUpdatedEvent.InputTuple,
      HashrateUpdatedEvent.OutputTuple,
      HashrateUpdatedEvent.OutputObject
    >;

    "MinerDeactivated(address,string)": TypedContractEvent<
      MinerDeactivatedEvent.InputTuple,
      MinerDeactivatedEvent.OutputTuple,
      MinerDeactivatedEvent.OutputObject
    >;
    MinerDeactivated: TypedContractEvent<
      MinerDeactivatedEvent.InputTuple,
      MinerDeactivatedEvent.OutputTuple,
      MinerDeactivatedEvent.OutputObject
    >;

    "MinerRegistered(address,uint256)": TypedContractEvent<
      MinerRegisteredEvent.InputTuple,
      MinerRegisteredEvent.OutputTuple,
      MinerRegisteredEvent.OutputObject
    >;
    MinerRegistered: TypedContractEvent<
      MinerRegisteredEvent.InputTuple,
      MinerRegisteredEvent.OutputTuple,
      MinerRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardParametersUpdated(uint256,uint256)": TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;
    RewardParametersUpdated: TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;

    "SuspiciousActivityDetected(address,uint256,string)": TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;
    SuspiciousActivityDetected: TypedContractEvent<
      SuspiciousActivityDetectedEvent.InputTuple,
      SuspiciousActivityDetectedEvent.OutputTuple,
      SuspiciousActivityDetectedEvent.OutputObject
    >;
  };
}
