/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SwapRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_BIPS"
      | "accumulatedEcosystemFee"
      | "accumulatedPlatformFee"
      | "addLiquidity"
      | "collectEcosystemFee"
      | "collectPlatformFee"
      | "ecosystemFeeShare"
      | "getPrice"
      | "initializeLiquidity"
      | "lpFeeShare"
      | "lpShares"
      | "owner"
      | "platformFeeShare"
      | "priceHistory"
      | "removeLiquidity"
      | "renounceOwnership"
      | "reserveSuper"
      | "reserveUSDT"
      | "superToken"
      | "swapSuperToUsdt"
      | "swapUsdtToSuper"
      | "totalLPShares"
      | "transferOwnership"
      | "usdtToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollected"
      | "LiquidityAdded"
      | "LiquidityRemoved"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "Swap"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FEE_BIPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "accumulatedEcosystemFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "accumulatedPlatformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectEcosystemFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectPlatformFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ecosystemFeeShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "initializeLiquidity",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpFeeShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lpShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveSuper",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveUSDT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "superToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapSuperToUsdt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapUsdtToSuper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLPShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdtToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "FEE_BIPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedEcosystemFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accumulatedPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectEcosystemFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ecosystemFeeShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpFeeShare", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveSuper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapSuperToUsdt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapUsdtToSuper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLPShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdtToken", data: BytesLike): Result;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [
    platformFee: BigNumberish,
    ecosystemFee: BigNumberish
  ];
  export type OutputTuple = [platformFee: bigint, ecosystemFee: bigint];
  export interface OutputObject {
    platformFee: bigint;
    ecosystemFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [
    provider: AddressLike,
    superAmount: BigNumberish,
    usdtAmount: BigNumberish,
    sharesIssued: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    superAmount: bigint,
    usdtAmount: bigint,
    sharesIssued: bigint
  ];
  export interface OutputObject {
    provider: string;
    superAmount: bigint;
    usdtAmount: bigint;
    sharesIssued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityRemovedEvent {
  export type InputTuple = [
    provider: AddressLike,
    superAmount: BigNumberish,
    usdtAmount: BigNumberish,
    sharesBurned: BigNumberish
  ];
  export type OutputTuple = [
    provider: string,
    superAmount: bigint,
    usdtAmount: bigint,
    sharesBurned: bigint
  ];
  export interface OutputObject {
    provider: string;
    superAmount: bigint;
    usdtAmount: bigint;
    sharesBurned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [priceSuperPerUSDT: BigNumberish];
  export type OutputTuple = [priceSuperPerUSDT: bigint];
  export interface OutputObject {
    priceSuperPerUSDT: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapEvent {
  export type InputTuple = [
    user: AddressLike,
    isSuperToUsdt: boolean,
    inputAmount: BigNumberish,
    outputAmount: BigNumberish,
    feeAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    isSuperToUsdt: boolean,
    inputAmount: bigint,
    outputAmount: bigint,
    feeAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    isSuperToUsdt: boolean;
    inputAmount: bigint;
    outputAmount: bigint;
    feeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SwapRouter extends BaseContract {
  connect(runner?: ContractRunner | null): SwapRouter;
  waitForDeployment(): Promise<this>;

  interface: SwapRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_BIPS: TypedContractMethod<[], [bigint], "view">;

  accumulatedEcosystemFee: TypedContractMethod<[], [bigint], "view">;

  accumulatedPlatformFee: TypedContractMethod<[], [bigint], "view">;

  addLiquidity: TypedContractMethod<
    [_superAmount: BigNumberish, _usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  collectEcosystemFee: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  collectPlatformFee: TypedContractMethod<[], [void], "nonpayable">;

  ecosystemFeeShare: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  initializeLiquidity: TypedContractMethod<
    [_superAmount: BigNumberish, _usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lpFeeShare: TypedContractMethod<[], [bigint], "view">;

  lpShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeShare: TypedContractMethod<[], [bigint], "view">;

  priceHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { timestamp: bigint; priceSuperPerUSDT: bigint }],
    "view"
  >;

  removeLiquidity: TypedContractMethod<
    [_sharesToBurn: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveSuper: TypedContractMethod<[], [bigint], "view">;

  reserveUSDT: TypedContractMethod<[], [bigint], "view">;

  superToken: TypedContractMethod<[], [string], "view">;

  swapSuperToUsdt: TypedContractMethod<
    [_superAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  swapUsdtToSuper: TypedContractMethod<
    [_usdtAmount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  totalLPShares: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdtToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_BIPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedEcosystemFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accumulatedPlatformFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addLiquidity"
  ): TypedContractMethod<
    [_superAmount: BigNumberish, _usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "collectEcosystemFee"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectPlatformFee"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ecosystemFeeShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initializeLiquidity"
  ): TypedContractMethod<
    [_superAmount: BigNumberish, _usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lpFeeShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint] & { timestamp: bigint; priceSuperPerUSDT: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeLiquidity"
  ): TypedContractMethod<[_sharesToBurn: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveSuper"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveUSDT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "superToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "swapSuperToUsdt"
  ): TypedContractMethod<[_superAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "swapUsdtToSuper"
  ): TypedContractMethod<[_usdtAmount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "totalLPShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdtToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityRemoved"
  ): TypedContractEvent<
    LiquidityRemovedEvent.InputTuple,
    LiquidityRemovedEvent.OutputTuple,
    LiquidityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Swap"
  ): TypedContractEvent<
    SwapEvent.InputTuple,
    SwapEvent.OutputTuple,
    SwapEvent.OutputObject
  >;

  filters: {
    "FeeCollected(uint256,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "LiquidityAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "LiquidityRemoved(address,uint256,uint256,uint256)": TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;
    LiquidityRemoved: TypedContractEvent<
      LiquidityRemovedEvent.InputTuple,
      LiquidityRemovedEvent.OutputTuple,
      LiquidityRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "Swap(address,bool,uint256,uint256,uint256)": TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
    Swap: TypedContractEvent<
      SwapEvent.InputTuple,
      SwapEvent.OutputTuple,
      SwapEvent.OutputObject
    >;
  };
}
